name: antipoff_group_test
description: E-commerce for Antipoff Group

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  material_color_gen: ^2.0.0
  eva_icons_flutter: ^3.1.0
  json_annotation: ^4.6.0
  connectivity_plus: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:

  assets:
    - images/

  uses-material-design: true
